// <auto-generated />
using System;
using GeekStore.Coupon.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekStore.Coupon.Data.Migrations
{
    [DbContext(typeof(CouponDataContext))]
    partial class CouponDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeekStore.Coupon.Domain.Coupons.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("846fe6e9-cdc0-4378-9349-0ee7f6ee0b2a"),
                            CouponCode = "GEEK10",
                            DiscountAmount = 10m
                        },
                        new
                        {
                            Id = new Guid("cb105c8d-c7d3-4c41-b6e3-e8a1492572b1"),
                            CouponCode = "GEEK20",
                            DiscountAmount = 20m
                        },
                        new
                        {
                            Id = new Guid("c309eadf-63f9-4f79-90b5-f2a61d6d5a64"),
                            CouponCode = "GEEK25",
                            DiscountAmount = 25m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
