// <auto-generated />
using System;
using GeekStore.Product.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekStore.Product.Data.Migrations
{
    [DbContext(typeof(ProductDataContext))]
    [Migration("20230317011138_seeds-produto")]
    partial class seedsproduto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeekStore.Product.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d75ab164-d6d1-4250-88ba-a4a2ede4443b"),
                            Category = "Star Wars",
                            Description = "Uma réplica em miniatura da icônica luz do sabre de luz de Star Wars",
                            ImageURL = "https://example.com/lightsaber.jpg",
                            Name = "Luz do Sabre de Luz",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = new Guid("80b982ee-ab71-493f-b02f-854b2a5909e5"),
                            Category = "Pokémon",
                            Description = "Uma réplica da pokebola usada para capturar pokemons no anime e jogo Pokémon",
                            ImageURL = "https://example.com/pokeball.jpg",
                            Name = "Pokebola",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = new Guid("4b5e329c-2687-437b-8cfa-745e654d1dc2"),
                            Category = "Tecnologia",
                            Description = "Óculos que proporcionam uma experiência de realidade virtual imersiva",
                            ImageURL = "https://example.com/vr-glasses.jpg",
                            Name = "Óculos de Realidade Virtual",
                            Price = 599.99m
                        },
                        new
                        {
                            Id = new Guid("91cd2751-1622-44c1-95e9-4b3fcef35fd3"),
                            Category = "Jogos",
                            Description = "Uma camiseta com o icônico personagem do jogo Pac-Man estampado",
                            ImageURL = "https://example.com/pacman-shirt.jpg",
                            Name = "Camiseta do Pac-Man",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = new Guid("4f99339f-b347-494a-a8ed-3b1d54f00665"),
                            Category = "Filmes",
                            Description = "Uma miniatura detalhada do carro DeLorean que viaja no tempo no filme De Volta para o Futuro",
                            ImageURL = "https://example.com/delorean.jpg",
                            Name = "Miniatura do DeLorean do De Volta para o Futuro",
                            Price = 149.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
